### ISSUE TITLE
Question: Remapping @ Shifted

### ISSUE THREAD

**Issue by Enteleform** [chrisandreae/keyboard-firmware#5]
Does this firmware allow separate mapping of the shifted layer?

For example, say I want to remap:

Key1: [ {
Key2: ] }

to 

Key1: [ ]
Key2: { }

**Comment by chrisandreae** [comment]
Yes and no. 

First, the no: actually splitting up keys that way isn't something that any keyboard can do, since the shifting isn't handled on the keyboard itself, but by the operating system. The keyboard merely sends the HID codes for both keys: eg. `0x2F (Keyboard [ and {)`  and `0xE1 (Keyboard LeftShift)`.

Second, the yes: you can instead use the firmware's macro functionality to achieve what you're after. If you create a macro on `shift + [` that presses `]`, and a macro on `]` that presses `shift + [`, you get the desired effect.
