### ISSUE TITLE
Question: tap vs hold and other ErgoDox-like keyboards supported?

### ISSUE THREAD

**Issue by jamadagni** [chrisandreae/keyboard-firmware#6]
Does this firmware provide the behaviour of "Oneshot modifier and modifier with tapping feature" provided by the TMK firmware as mentioned at https://github.com/tmk/tmk_keyboard/?

If only that then this seems the ideal choice for my ErgoDox.

Also, if anyone were to make a modded version of the ErgoDox with less/more keys, would it be relatively simple to adapt this firmware for that too?

**Comment by chrisandreae** [comment]
I'm currently not planning to add specific functionality for these, however you may be able to use the macro language to imitate them.

For example - a "sticky" modifier that affects the next normal keystroke:

``` C
void main(){
    byte modifier = 0xE1; // left shift

    // Press the modifier
    pressKey(modifier);

    // wait for initial key to be released
    while(checkPhysKey(0)){}

    // Now wait for any other key to be pressed
    byte b = waitKey(0, 0);

    // and drop our sticky modifier
    releaseKey(modifier);
}
```

A dual tap vs hold key+modifier combination is slightly more difficult, because the macro trigger system looks at all keys pressed at once: for example, a macro on "A" will not be triggered by pressing "Shift + A". That said, it works fine for a key that you don't use with modifiers:

``` C
void main(){
    byte modifierKey = 0xE1; // Left shift
    byte tapKey      = 0x04; // A

    byte isModifier = 0;

    // save the time
    short t = getUptimeMS();
    // and wait for the key to be released
    while(checkPhysKey(0)){
        // if we're over our tap threshold (100ms), press the modifier
        if((getUptimeMS() - t) > 100){
            pressKey(modifierKey); // left shift
            isModifier = 1;
        }
    }

    if(isModifier){
        releaseKey(modifierKey);
    }
    else{
        // tapped
        pressKey(tapKey);
        releaseKey(tapKey);
    }
}
```

> Also, if anyone were to make a modded version of the ErgoDox with less/more keys, would it be relatively simple to adapt this firmware for that too?

Yeah, adapting to another AVR-based keyboard is pretty straightforward. Have a look at the three examples in `hardware/`: `kinesis`, `kinesis110` and `ergodox`.
